import type { Creation } from "@/types";

export const mockCreations: Creation[] = [
  {
    id: "c1",
    bookId: "guns-germs-steel",
    userId: "user1",
    userName: "아트민수",
    title: "얄리와 다이아몬드 스티커 세트",
    description: "총균쇠 캐릭터들을 귀여운 스티커로 만들었어요!",
    type: "sticker",
    fileUrl: "",
    thumbnailUrl: "/covers/creation1.jpg",
    tags: ["캐릭터", "얄리", "스티커"],
    status: "approved",
    likes: 42,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-01",
  },
  {
    id: "c2",
    bookId: "guns-germs-steel",
    userId: "user2",
    userName: "음악하는독자",
    title: "비옥한 초승달 OST",
    description: "제2장 식량 생산의 힘에서 영감받은 오리지널 음악",
    type: "music",
    fileUrl: "",
    thumbnailUrl: "/covers/creation2.jpg",
    tags: ["OST", "어쿠스틱"],
    status: "approved",
    likes: 28,
    ogqLinked: false,
    createdAt: "2024-12-05",
  },
  {
    id: "c3",
    bookId: "guns-germs-steel",
    userId: "user3",
    userName: "웹툰작가지망",
    title: "총균쇠 숏툰 - 얄리의 여행",
    description: "얄리의 시점으로 본 세계 문명 탐험기",
    type: "webtoon",
    fileUrl: "",
    thumbnailUrl: "/covers/creation3.jpg",
    tags: ["숏툰", "얄리", "모험"],
    status: "approved",
    likes: 56,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-10",
  },
  {
    id: "c4",
    bookId: "guns-germs-steel",
    userId: "user4",
    userName: "영상크리에이터",
    title: "3분 요약 - 가축화의 비밀",
    description: "제3장을 3분 영상으로 정리해봤습니다",
    type: "video",
    fileUrl: "",
    thumbnailUrl: "/covers/creation4.jpg",
    tags: ["요약", "영상", "가축화"],
    status: "approved",
    likes: 35,
    ogqLinked: false,
    createdAt: "2024-12-15",
  },
  {
    id: "c5",
    bookId: "guns-germs-steel",
    userId: "user5",
    userName: "소설가지니",
    title: "만약 얄리가 유럽에서 태어났다면",
    description: "IF 시나리오 숏북. 얄리가 유럽 탐험가였다면?",
    type: "novel",
    fileUrl: "",
    thumbnailUrl: "/covers/creation5.jpg",
    tags: ["IF", "대체역사", "소설"],
    status: "approved",
    likes: 19,
    ogqLinked: false,
    createdAt: "2024-12-20",
  },
  {
    id: "c6",
    bookId: "guns-germs-steel",
    userId: "user1",
    userName: "아트민수",
    title: "고대 농경 일러스트 세트",
    description: "비옥한 초승달 지대의 풍경을 일러스트로 그렸습니다",
    type: "photo",
    fileUrl: "",
    thumbnailUrl: "/covers/creation6.jpg",
    tags: ["일러스트", "농경", "풍경"],
    status: "approved",
    likes: 31,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-25",
  },
];

export function getCreationsByBookId(bookId: string): Creation[] {
  return mockCreations.filter((c) => c.bookId === bookId);
}
