import type { Creation } from "@/types";

export const mockCreations: Creation[] = [
  {
    id: "c1",
    bookId: "guns-germs-steel",
    userId: "user1",
    userName: "아트민수",
    title: "얄리와 다이아몬드 스티커 세트",
    description: "총균쇠 캐릭터들을 귀여운 스티커로 만들었어요!",
    type: "sticker",
    fileUrl: "",
    thumbnailUrl: "/covers/creation1.jpg",
    tags: ["캐릭터", "얄리", "스티커"],
    status: "approved",
    likes: 42,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-01",
  },
  {
    id: "c2",
    bookId: "guns-germs-steel",
    userId: "user2",
    userName: "음악하는독자",
    title: "비옥한 초승달 OST",
    description: "제2장 식량 생산의 힘에서 영감받은 오리지널 음악",
    type: "music",
    fileUrl: "",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    thumbnailUrl: "/covers/creation2.jpg",
    tags: ["OST", "어쿠스틱"],
    status: "approved",
    likes: 28,
    ogqLinked: false,
    createdAt: "2024-12-05",
  },
  {
    id: "c3",
    bookId: "guns-germs-steel",
    userId: "user3",
    userName: "웹툰작가지망",
    title: "총균쇠 숏툰 - 얄리의 여행",
    description: "얄리의 시점으로 본 세계 문명 탐험기",
    type: "webtoon",
    fileUrl: "",
    thumbnailUrl: "/covers/creation3.jpg",
    tags: ["숏툰", "얄리", "모험"],
    status: "approved",
    likes: 56,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-10",
  },
  {
    id: "c4",
    bookId: "guns-germs-steel",
    userId: "user4",
    userName: "영상크리에이터",
    title: "3분 요약 - 가축화의 비밀",
    description: "제3장을 3분 영상으로 정리해봤습니다",
    type: "video",
    fileUrl: "",
    thumbnailUrl: "/covers/creation4.jpg",
    tags: ["요약", "영상", "가축화"],
    status: "approved",
    likes: 35,
    ogqLinked: false,
    createdAt: "2024-12-15",
  },
  {
    id: "c5",
    bookId: "guns-germs-steel",
    userId: "user5",
    userName: "소설가지니",
    title: "만약 얄리가 유럽에서 태어났다면",
    description: "IF 시나리오 숏북. 얄리가 유럽 탐험가였다면?",
    type: "novel",
    fileUrl: "",
    thumbnailUrl: "/covers/creation5.jpg",
    tags: ["IF", "대체역사", "소설"],
    status: "approved",
    likes: 19,
    ogqLinked: false,
    createdAt: "2024-12-20",
  },
  {
    id: "c6",
    bookId: "guns-germs-steel",
    userId: "user1",
    userName: "아트민수",
    title: "고대 농경 일러스트 세트",
    description: "비옥한 초승달 지대의 풍경을 일러스트로 그렸습니다",
    type: "photo",
    fileUrl: "",
    thumbnailUrl: "/covers/creation6.jpg",
    tags: ["일러스트", "농경", "풍경"],
    status: "approved",
    likes: 31,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-25",
  },
];

// lovers-lover 책 창작물
export const loversCreations: Creation[] = [
  {
    id: "ll-c1",
    bookId: "lovers-lover",
    userId: "user10",
    userName: "콤니니",
    title: "수연의 편지 스티커팩",
    description: "수연이 보내지 못한 편지들을 감성 스티커로 만들었어요",
    type: "sticker",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["수연", "편지", "감성스티커"],
    status: "approved",
    likes: 38,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2025-01-10",
  },
  {
    id: "ll-c3",
    bookId: "lovers-lover",
    userId: "user12",
    userName: "웹툰작가지망",
    title: "수연과 지호 - 숏툰",
    description: "두 사람의 엇갈린 마음을 4컷 만화로 그려봤어요",
    type: "webtoon",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["숏툰", "수연", "지호"],
    status: "approved",
    likes: 47,
    ogqLinked: false,
    createdAt: "2025-01-20",
  },
  {
    id: "ll-c4",
    bookId: "lovers-lover",
    userId: "user13",
    userName: "소설가지니",
    title: "만약 수연이 먼저 말했다면",
    description: "IF 시나리오. 수연이 용기를 냈다면 결말이 어떻게 바뀌었을까?",
    type: "novel",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["IF", "대체결말", "소설"],
    status: "approved",
    likes: 33,
    ogqLinked: false,
    createdAt: "2025-02-01",
  },
  {
    id: "ll-c5",
    bookId: "lovers-lover",
    userId: "user14",
    userName: "영상크리에이터",
    title: "애인의 애인에게 - 북트레일러",
    description: "이 책의 감성을 1분 영상으로 담아봤습니다",
    type: "video",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["북트레일러", "영상", "감성"],
    status: "approved",
    likes: 29,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2025-02-10",
  },
  {
    id: "ll-c6",
    bookId: "lovers-lover",
    userId: "user15",
    userName: "피아니스트K",
    title: "재현의 테마 - 이별 후",
    description: "재현의 복잡한 감정을 담은 피아노 솔로",
    type: "music",
    fileUrl: "",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    thumbnailUrl: "",
    tags: ["피아노", "이별", "감성"],
    status: "approved",
    likes: 19,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2025-02-15",
  },
  {
    id: "ll-m-apiframe-1",
    bookId: "lovers-lover",
    userId: "daeunhoshi@gmail.com",
    userName: "음악하는독자",
    title: "애인의 애인에게 감성 음악",
    description: "책의 감성을 담은 AI 생성 음악",
    type: "music",
    fileUrl: "",
    audioUrl: "https://cdn.apiframe.pro/songs/61644855558960688680011761952548-1.mp3",
    thumbnailUrl: "https://musicfile.kie.ai/M2JjM2QxYTMtYjQ4MC00MGI0LTk1NjktMzkzY2VhZTI5ZjRm.jpeg",
    tags: ["감성", "피아노", "ambient"],
    status: "approved",
    likes: 0,
    ogqLinked: false,
    createdAt: "2026-04-09",
  },
];

const otherBooksMusic: Creation[] = [
  { id: "dkm-m1", bookId: "dont-know-myself", userId: "u20", userName: "피아노솔로", title: "마음의 지도", description: "자아 탐색의 여정을 피아노로", type: "music", fileUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3", thumbnailUrl: "", tags: ["피아노", "힐링"], status: "approved", likes: 22, ogqLinked: false, createdAt: "2025-02-01" },
  { id: "dkm-m2", bookId: "dont-know-myself", userId: "u21", userName: "어쿠스틱밴드", title: "내면의 목소리", description: "내면과의 대화를 어쿠스틱으로", type: "music", fileUrl: "", thumbnailUrl: "", tags: ["어쿠스틱"], status: "approved", likes: 15, ogqLinked: true, ogqUrl: "https://ogq.me", createdAt: "2025-02-05" },
  { id: "wmm-m1", bookId: "what-moves-me", userId: "u22", userName: "명상음악가", title: "고요한 새벽", description: "선방의 새벽 고요함", type: "music", fileUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3", thumbnailUrl: "", tags: ["명상", "앰비언트"], status: "approved", likes: 18, ogqLinked: false, createdAt: "2025-01-20" },
  { id: "wmm-m2", bookId: "what-moves-me", userId: "u23", userName: "첼로앙상블", title: "깨달음의 순간", description: "깊은 사유를 첼로로", type: "music", fileUrl: "", thumbnailUrl: "", tags: ["첼로", "클래식"], status: "approved", likes: 12, ogqLinked: true, ogqUrl: "https://ogq.me", createdAt: "2025-01-25" },
  { id: "dp-m1", bookId: "difficult-people", userId: "u24", userName: "Lo-Fi스튜디오", title: "집중의 시간", description: "업무 집중용 Lo-Fi", type: "music", fileUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3", thumbnailUrl: "", tags: ["Lo-Fi", "집중"], status: "approved", likes: 31, ogqLinked: false, createdAt: "2025-02-10" },
  { id: "dp-m2", bookId: "difficult-people", userId: "u25", userName: "재즈트리오", title: "협업의 리듬", description: "함께 일하는 리듬감", type: "music", fileUrl: "", thumbnailUrl: "", tags: ["재즈"], status: "approved", likes: 9, ogqLinked: true, ogqUrl: "https://ogq.me", createdAt: "2025-02-15" },
  { id: "dh-m1", bookId: "dragon-hero-3", userId: "u26", userName: "오케스트라K", title: "불꽃의 전설", description: "드래곤과의 모험 OST", type: "music", fileUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3", thumbnailUrl: "", tags: ["오케스트라", "판타지"], status: "approved", likes: 27, ogqLinked: false, createdAt: "2025-01-30" },
  { id: "dh-m2", bookId: "dragon-hero-3", userId: "u27", userName: "심포니앙상블", title: "용사의 여정", description: "카이의 성장 테마", type: "music", fileUrl: "", thumbnailUrl: "", tags: ["심포니", "모험"], status: "approved", likes: 16, ogqLinked: true, ogqUrl: "https://ogq.me", createdAt: "2025-02-02" },
  { id: "bph-m1", bookId: "big-pumpkin-house", userId: "u28", userName: "동화음악단", title: "따뜻한 오후", description: "호박집의 평화로운 오후", type: "music", fileUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3", thumbnailUrl: "", tags: ["동화", "따뜻한"], status: "approved", likes: 20, ogqLinked: false, createdAt: "2025-01-18" },
  { id: "slu-m1", bookId: "science-level-up-4", userId: "u29", userName: "일렉트로팝", title: "신나는 실험실", description: "과학 실험처럼 신나는 비트", type: "music", fileUrl: "", audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3", thumbnailUrl: "", tags: ["일렉트로닉", "신남"], status: "approved", likes: 24, ogqLinked: false, createdAt: "2025-02-08" },
];

const allCreations = [...mockCreations, ...loversCreations, ...otherBooksMusic];

export function getCreationsByBookId(bookId: string): Creation[] {
  return allCreations.filter((c) => c.bookId === bookId);
}

export function getCreationById(id: string): Creation | undefined {
  return allCreations.find((c) => c.id === id);
}
