import type { Creation } from "@/types";

export const mockCreations: Creation[] = [
  {
    id: "c1",
    bookId: "guns-germs-steel",
    userId: "user1",
    userName: "아트민수",
    title: "얄리와 다이아몬드 스티커 세트",
    description: "총균쇠 캐릭터들을 귀여운 스티커로 만들었어요!",
    type: "sticker",
    fileUrl: "",
    thumbnailUrl: "/covers/creation1.jpg",
    tags: ["캐릭터", "얄리", "스티커"],
    status: "approved",
    likes: 42,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-01",
  },
  {
    id: "c2",
    bookId: "guns-germs-steel",
    userId: "user2",
    userName: "음악하는독자",
    title: "비옥한 초승달 OST",
    description: "제2장 식량 생산의 힘에서 영감받은 오리지널 음악",
    type: "music",
    fileUrl: "",
    thumbnailUrl: "/covers/creation2.jpg",
    tags: ["OST", "어쿠스틱"],
    status: "approved",
    likes: 28,
    ogqLinked: false,
    createdAt: "2024-12-05",
  },
  {
    id: "c3",
    bookId: "guns-germs-steel",
    userId: "user3",
    userName: "웹툰작가지망",
    title: "총균쇠 숏툰 - 얄리의 여행",
    description: "얄리의 시점으로 본 세계 문명 탐험기",
    type: "webtoon",
    fileUrl: "",
    thumbnailUrl: "/covers/creation3.jpg",
    tags: ["숏툰", "얄리", "모험"],
    status: "approved",
    likes: 56,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-10",
  },
  {
    id: "c4",
    bookId: "guns-germs-steel",
    userId: "user4",
    userName: "영상크리에이터",
    title: "3분 요약 - 가축화의 비밀",
    description: "제3장을 3분 영상으로 정리해봤습니다",
    type: "video",
    fileUrl: "",
    thumbnailUrl: "/covers/creation4.jpg",
    tags: ["요약", "영상", "가축화"],
    status: "approved",
    likes: 35,
    ogqLinked: false,
    createdAt: "2024-12-15",
  },
  {
    id: "c5",
    bookId: "guns-germs-steel",
    userId: "user5",
    userName: "소설가지니",
    title: "만약 얄리가 유럽에서 태어났다면",
    description: "IF 시나리오 숏북. 얄리가 유럽 탐험가였다면?",
    type: "novel",
    fileUrl: "",
    thumbnailUrl: "/covers/creation5.jpg",
    tags: ["IF", "대체역사", "소설"],
    status: "approved",
    likes: 19,
    ogqLinked: false,
    createdAt: "2024-12-20",
  },
  {
    id: "c6",
    bookId: "guns-germs-steel",
    userId: "user1",
    userName: "아트민수",
    title: "고대 농경 일러스트 세트",
    description: "비옥한 초승달 지대의 풍경을 일러스트로 그렸습니다",
    type: "photo",
    fileUrl: "",
    thumbnailUrl: "/covers/creation6.jpg",
    tags: ["일러스트", "농경", "풍경"],
    status: "approved",
    likes: 31,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2024-12-25",
  },
];

// lovers-lover 책 창작물
export const loversCreations: Creation[] = [
  {
    id: "ll-c1",
    bookId: "lovers-lover",
    userId: "user10",
    userName: "콤니니",
    title: "수연의 편지 스티커팩",
    description: "수연이 보내지 못한 편지들을 감성 스티커로 만들었어요",
    type: "sticker",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["수연", "편지", "감성스티커"],
    status: "approved",
    likes: 38,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2025-01-10",
  },
  {
    id: "ll-c2",
    bookId: "lovers-lover",
    userId: "user11",
    userName: "음악하는독자",
    title: "애인의 애인에게 OST - 빗소리",
    description: "3장에서 영감받은 피아노 연주곡. 빗소리와 함께 듣기 좋아요.",
    type: "music",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["OST", "피아노", "감성"],
    status: "approved",
    likes: 25,
    ogqLinked: false,
    createdAt: "2025-01-15",
  },
  {
    id: "ll-c3",
    bookId: "lovers-lover",
    userId: "user12",
    userName: "웹툰작가지망",
    title: "수연과 지호 - 숏툰",
    description: "두 사람의 엇갈린 마음을 4컷 만화로 그려봤어요",
    type: "webtoon",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["숏툰", "수연", "지호"],
    status: "approved",
    likes: 47,
    ogqLinked: false,
    createdAt: "2025-01-20",
  },
  {
    id: "ll-c4",
    bookId: "lovers-lover",
    userId: "user13",
    userName: "소설가지니",
    title: "만약 수연이 먼저 말했다면",
    description: "IF 시나리오. 수연이 용기를 냈다면 결말이 어떻게 바뀌었을까?",
    type: "novel",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["IF", "대체결말", "소설"],
    status: "approved",
    likes: 33,
    ogqLinked: false,
    createdAt: "2025-02-01",
  },
  {
    id: "ll-c5",
    bookId: "lovers-lover",
    userId: "user14",
    userName: "영상크리에이터",
    title: "애인의 애인에게 - 북트레일러",
    description: "이 책의 감성을 1분 영상으로 담아봤습니다",
    type: "video",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["북트레일러", "영상", "감성"],
    status: "approved",
    likes: 29,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2025-02-10",
  },
  {
    id: "ll-c6",
    bookId: "lovers-lover",
    userId: "user15",
    userName: "음악하는독자",
    title: "빗속의 재회 - 앰비언트 OST",
    description: "수연이 재현을 마지막으로 본 날, 빗소리 속에서 피어나는 멜로디를 담았어요.",
    type: "music",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["OST", "앰비언트", "피아노", "빗소리"],
    status: "approved",
    likes: 41,
    ogqLinked: false,
    createdAt: "2025-02-15",
  },
  {
    id: "ll-c7",
    bookId: "lovers-lover",
    userId: "user16",
    userName: "재즈덕후",
    title: "애인의 애인에게 - 재즈 버전",
    description: "책의 복잡한 감정선을 재즈 스타일로 표현했어요. 색소폰이 수연의 마음을 대변해요.",
    type: "music",
    fileUrl: "",
    thumbnailUrl: "",
    tags: ["재즈", "색소폰", "수연"],
    status: "approved",
    likes: 29,
    ogqLinked: true,
    ogqUrl: "https://ogq.me",
    createdAt: "2025-02-20",
  },
];

const allCreations = [...mockCreations, ...loversCreations];

export function getCreationsByBookId(bookId: string): Creation[] {
  return allCreations.filter((c) => c.bookId === bookId);
}

export function getCreationById(id: string): Creation | undefined {
  return allCreations.find((c) => c.id === id);
}
